### ISSUE TITLE
Dinosaurs example works slightly differently with Bevy 0.12

### ISSUE THREAD

**Issue by 5tr1k3r** [sparten11740/bevy_health_bar3d#23]
There is a tiny discrepancy between how it previously worked and how it works now, with Bevy 0.12. After one of the dinosaurs dies, it does the death animation, but after it's finished, the dinosaur mesh is reset to the initial position (instead of continuing to lie on the ground).

This is basically not important at all for the purposes of demonstrating the bar plugin :D But I figured since I spotted that, it deserves a mention.

**Comment by 5tr1k3r** [comment]
https://github.com/bevyengine/bevy/issues/10480 might be this but I'm not 100% positive

**Comment by sparten11740** [comment]
you're right, it's been fixed in https://github.com/bevyengine/bevy/pull/10540, just gotta wait for a release
